# ValueError
s='one'
print(int(s))